import Head from 'next/head'
import axios from 'axios';
import React, { Component } from 'react';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Router from 'next/router'
import cookie from 'react-cookies'
class index extends Component {

  host = ""
  componentDidMount() {
   /* const expires = new Date()
    expires.setDate(Date.now() + 1000 * 60 * 60 * 24 * 14)
    cookie.remove('loginInfo', { path: '/' })
    cookie.remove('host', { path: '/' })
    cookie.save('host', { host: 'http://localhost:2022/node' }, { path: '/', expires, maxAge: 1000 })
    var host= cookie.load('host');
    this.host=host.host*/
  }
  constructor() {
    super()
    this.state = {
      redirect:0

    }
  }

  onchg = (event) => {

    var name = event.target.name;
    var value = event.target.value;
    this.setState({ [name]: value }, () => { });

  }
  submit = async e => {


    axios
      .post(this.host + '/login', this.state)
      .then(response => {

        
        this.setState({ redirect: 1 }, () => { });

       

        axios.defaults.headers = {
          user_id: response.data[2][0].user_id,
          Token: response.data[2][0].token,
      }

      })
      .catch(error => {
        toast.error("Invalid Credentials", {
          theme: "colored",
          autoClose: 1000
        })
      })
  }



  render() {
    if (this.state.redirect == 1) {
     
      Router.push('/Form/ApplicationPage')
  }else
    return (


      <div>
        <Head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
          <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" type="image/x-icon" />

          <link rel="stylesheet" href="/assets/plugins/bootstrap/css/bootstrap.min.css" />

          <link rel="stylesheet" href="/assets/css/style.min.css" />
        </Head>
        <main className={"font-muli theme-cyan gradient"}>

          <div className="auth option2">
            <div className="auth_left">
              <div className="card">
                <div className="card-body">
                  <div className="text-center">
                    <a className="header-brand" href="index.html"><i className="fa fa-graduation-cap brand-logo" /></a>
                    <div className="card-title mt-3">Login to your account</div>
                    <button type="button" className="btn btn-facebook"><i className="fa fa-facebook mr-2" />Facebook</button>
                    <button type="button" className="btn btn-google"><i className="fa fa-google mr-2" />Google</button>
                    <h6 className="mt-3 mb-3">Or</h6>
                  </div>
                  <div className="form-group">
                    <input type="text" className="form-control" id="userID" name="userID" onChange={this.onchg} aria-describedby="emailHelp" placeholder="Enter email" />
                  </div>
                  <div className="form-group">
                    <label className="form-label"><a href="forgot-password.html" className="float-right small">I forgot password</a></label>
                    <input type="password" className="form-control" id="password" name="password" onChange={this.onchg} placeholder="Password" />
                  </div>
                  <div className="form-group">
                    <label className="custom-control custom-checkbox">
                      <input type="checkbox" className="custom-control-input" />
                      <span className="custom-control-label">Remember me</span>
                    </label>
                  </div>
                  <div className="text-center">
                    <button onClick={this.submit} className="btn btn-primary btn-block" >Sign in</button>
                    <div className="text-muted mt-4">Don't have account yet? <a href="register.html">Sign up</a></div>
                    <ToastContainer />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>

      </div>

    )
  }
}

export default index;
